CREATE TABLE CLIENTES (
ID_CLIENTES INT,
NOMBRE VARCHAR(100),
PERFIL_BIO VARCHAR(MAX),
FECHA_REGISTRO DATE
);

CREATE TABLE PRODUCTOS (
ID_PRODUCTO INT,
DESCRIPCION VARCHAR(255),
PRECIO DECIMAL(10,2),
ESTA_ACTIVO INT -- SE TOMA ENTERO PARA DEFINIR 0 SI ESTA INACTIVO Y 1 SI ES ACTIVO
);
